export const STATUS = {
  SELECTED_NOTIFIED: 'SELECTED_NOTIFIED',
  INTERESTED: 'INTERESTED',
  NDA_SIGNED: 'NDA_SIGNED',
  NBO_SUBMITTED: 'NBO_SUBMITTED',
  DUE_DILIGENCE: 'DUE_DILIGENCE',
  VISIT: 'VISIT',
  BO_SUBMITTED: 'BO_SUBMITTED',
  CLOSING: 'CLOSING',
};

export const DEAL_STATUS = {
  LOST: 'LOST',
  ACTIVE: 'ACTIVE',
};

export const DEAL_STATUS_VALUE = {
  NDA: 0,
  NBO: 1,
  BO: 2,
  CLOSING: 3,
};

export const FILE_TYPE = {
  NDA: 'NDA',
  TEASER: 'TEASER',
  SALES_MEMO: 'SALES_MEMO', 
  BUILDING_PLAN: 'BUILDING_PLAN',
  COMMERCIAL_REGISTER: 'COMMERCIAL_REGISTER',
  RENTAL_STATUS: 'RENTAL_STATUS',
  BO_SUBMITTED: 'BO_SUBMITTED',
  POA: 'POA',
  SELLING_ACT: 'SELLING_ACT',
  LFAIE: 'LFAIE',
  POWER_OF_ATTORNY: 'POWER_OF_ATTORNY'
}
