import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/Home.module.css';
import { useRouter } from 'next/router';
import Link from 'next/link';

type RequiredAuthNextPageWithLayout = NextPage & {
  requireAuth?: boolean;
};

const Details: RequiredAuthNextPageWithLayout = () => {
  const { locale, locales, asPath } = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Deal Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.navbar}>
          <Link href="/">
            <a>Home</a>
          </Link>
          <ul>
            <li>
              <Link href="/details" locale="de">
                <a>Details in Germany</a>
              </Link>
            </li>
            <li>
              <Link href="/details" locale="en">
                <a>Details in English</a>
              </Link>
            </li>
            <li>
              <Link href="/details" locale="fr">
                <a>Details in French</a>
              </Link>
            </li>
          </ul>
          <br />
          {locales && locales.map((l, i) => {
            return (
              <span key={i} className={l === locale ? styles.selected : ''}>
                <Link href={asPath} locale={l}>
                  {l}
                </Link>
                &nbsp;
              </span>
            );
          })}
        </div>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

Details.requireAuth = true;
export default Details;
