import type { NextPage } from 'next';
import * as React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '@styles/Home.module.css';
import { useRouter } from 'next/router';
import useTrans from '@hooks/useTrans';
import { LoginForm } from '@components/login/LoginForm';
import { RequestAccessForm } from '@components/requestAccess/RequestAccessForm';
import { Container, Typography, Box, Grid } from '@mui/material';
import { useAuth } from '../components/auth/AuthProvider';
import LayoutNotLogin from '@components/layout/layout-not-login';

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

const Home: NextPageWithLayout = () => {
  const trans = useTrans();
  const [formState, setFormState] = React.useState<'login' | 'signin'>('login');

  const { auth } = useAuth();
  const router = useRouter();
  if (auth.user) {
    router.push('/overview');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.biuuIv}>
        <Container maxWidth="lg">
          <Box mt={{ xs: 6, sm: 8, md: 16 }} mb={4}>
            <Grid container spacing={4}>
              <Grid item xs={12} sm={8} md={6}>
                <div>
                  {formState === 'login' && (
                    <LoginForm
                      showRequestAccessForm={() => {
                        setFormState('signin');
                      }}
                    />
                  )}
                  {formState === 'signin' && (
                    <RequestAccessForm
                      showRequestAccessForm={() => {
                        setFormState('login');
                      }}
                    />
                  )}
                </div>
              </Grid>
            </Grid>
          </Box>
        </Container>
      </div>
      <Container maxWidth="lg">
        <Box my={6} pb={15}>
          <Grid container spacing={10}>
            <Grid item xs={12} sm={6}>
              <Box textAlign={{ xs: 'center', sm: 'initial' }}>
                <Typography
                  variant="h6"
                  paragraph={true}
                  className={styles.yourContactTitle}
                >
                  {trans.common['aboutRealadvisor']}
                </Typography>
                <Typography
                  variant="body1"
                  paragraph
                  style={{ whiteSpace: 'pre-line' }}
                  className={styles.aboutParagraph}
                >
                  {trans.common['aboutRealadvisorParagaph1']}
                </Typography>
                <Typography
                  variant="body1"
                  style={{ whiteSpace: 'pre-line' }}
                  className={styles.aboutParagraph}
                  mt={4}
                >
                  {trans.common['aboutRealadvisorParagaph2']}
                </Typography>
              </Box>
            </Grid>
            <Grid item xs={12} sm={6}>
              <Box textAlign={{ xs: 'center', sm: 'initial' }}>
                <Typography
                  variant="h6"
                  paragraph={true}
                  className={styles.yourContactTitle}
                >
                  {trans.common['yourContact']}
                </Typography>
                <Grid container>
                  <Grid item xs="auto">
                    <div style={{ paddingRight: '20px' }}>
                      <div
                        style={{
                          width: '126px',
                          height: '126px',
                          position: 'relative',
                          borderRadius: '50%',
                          overflow: 'hidden',
                        }}
                      >
                        <Image
                          src="/images/CarmeloLombardo.jpg"
                          alt="Real advisor"
                          width="100%"
                          height="100%"
                          layout="responsive"
                          objectFit="contain"
                          quality={100}
                        />
                      </div>
                    </div>
                  </Grid>
                  <Grid item xs="auto">
                    <div>
                      <Typography
                        variant="h6"
                        paragraph={true}
                        className="yourContactName"
                        mt={2}
                      >
                        Carmelo Lombardo
                      </Typography>
                      <Typography
                        variant="body1"
                        style={{ whiteSpace: 'pre-line' }}
                        mt={0}
                        className="aboutParagraph"
                      >
                        {trans.common['headOfInvestmentRealEstate']}
                      </Typography>
                      <Typography
                        variant="body1"
                        style={{ whiteSpace: 'pre-line' }}
                        mt={0}
                        className="aboutParagraph"
                      >
                        +41 79 442 41 07
                      </Typography>
                      <Typography
                        variant="body1"
                        style={{ whiteSpace: 'pre-line' }}
                        mt={0}
                        className="aboutParagraph"
                      >
                        <a href={`mailto:carmelo@realadvisor.com`} >
                          carmelo@realadvisor.com
                        </a>
                      </Typography>
                    </div>
                  </Grid>
                </Grid>
              </Box>
            </Grid>
          </Grid>
        </Box>
      </Container>
    </div>
  );
};

Home.getLayout = function getLayout(page: React.ReactElement) {
  return <LayoutNotLogin>{page}</LayoutNotLogin>;
};

export default Home;
